In [1]:
import numpy as np

## Data Types and Attributes

In [2]:
# NumPy main datatype in ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2, 3],
              [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [5]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape

(2, 3, 3)

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a1.ndim, a3.ndim

(1, 3)

In [11]:
a1.size

3

In [12]:
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

## Creating NumPy array

In [13]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [14]:
sample_array.dtype

dtype('int32')

In [15]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
ones.dtype

dtype('float64')

In [17]:
type(ones)

numpy.ndarray

In [18]:
zeros = np.zeros((2, 5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [20]:
import random
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[5, 8, 3, 3, 2],
       [0, 8, 9, 9, 3],
       [7, 2, 1, 6, 3]])

In [21]:
random_array.size

15

In [22]:
random_array.shape

(3, 5)

In [24]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.21997811, 0.8255861 , 0.43585122],
       [0.25059813, 0.74284246, 0.19847392],
       [0.12753308, 0.93724714, 0.54754448],
       [0.11203253, 0.50742706, 0.75107091],
       [0.80480862, 0.66546816, 0.80542189]])

In [25]:
random_array_2.shape

(5, 3)

In [27]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.502528  , 0.73215205, 0.52885354],
       [0.236077  , 0.86733889, 0.62183334],
       [0.49618032, 0.43146572, 0.97981259],
       [0.54011423, 0.51030268, 0.90906128],
       [0.67774185, 0.85775794, 0.15006889]])

In [29]:
# Pseudo random numbers
np.random.seed(42)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])