In [1]:
import tensorflow as tf

1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant()

In [9]:
Scalar = tf.constant([6])
print(Scalar)

Vector = tf.constant([6, 9])
print(Vector)

Tensor = tf.constant([[2,3,1],
                     [6,8,11]])
print(Tensor)

tf.Tensor([6], shape=(1,), dtype=int32)
tf.Tensor([6 9], shape=(2,), dtype=int32)
tf.Tensor(
[[ 2  3  1]
 [ 6  8 11]], shape=(2, 3), dtype=int32)


2. Find the shape, rank and size of the tensors you created in 1.


In [14]:
print(Tensor.shape)
print(tf.rank(Tensor))
print(tf.size(Tensor))

(2, 3)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


3. Create two tensors containing random values between 0 and 1 with shape [5, 300]

In [21]:
tensor1 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)
print(tensor1, "\n")

tensor2 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)
print(tensor2)

tf.Tensor(
[[0.98282814 0.48366404 0.4255004  ... 0.77844286 0.18097389 0.01318359]
 [0.40004313 0.7983149  0.5930133  ... 0.71320164 0.66150475 0.66573   ]
 [0.54890347 0.9911114  0.30962086 ... 0.26520395 0.96542585 0.09316742]
 [0.22418082 0.19316506 0.4629383  ... 0.7898017  0.57257223 0.8682287 ]
 [0.6752553  0.6397582  0.0131532  ... 0.7859386  0.9868463  0.53480446]], shape=(5, 300), dtype=float32) 

tf.Tensor(
[[0.12114942 0.5130514  0.626397   ... 0.05785298 0.59684646 0.5284895 ]
 [0.07670867 0.30844223 0.09478569 ... 0.15125275 0.31358528 0.7472644 ]
 [0.19608712 0.44618022 0.12489867 ... 0.336017   0.51908445 0.26229775]
 [0.4050635  0.39610016 0.02780294 ... 0.40166712 0.5650922  0.62358034]
 [0.7761489  0.22450113 0.59483016 ... 0.5033041  0.30096114 0.74274564]], shape=(5, 300), dtype=float32)


4. Multiply the two tensors you created in 3 using matrix multiplication.


In [22]:
tf.matmul(tensor1, tf.transpose(tensor2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[67.996216, 72.29039 , 70.0408  , 78.776566, 74.27845 ],
       [68.932205, 67.911125, 66.19202 , 73.86763 , 72.70264 ],
       [75.368546, 76.299126, 71.6873  , 83.935974, 80.64215 ],
       [70.1219  , 70.58983 , 69.68103 , 79.3739  , 76.150696],
       [68.195366, 70.41446 , 67.80717 , 75.09886 , 73.66534 ]],
      dtype=float32)>

5. Multiply the two tensors you created in 3 using dot product.


In [24]:
tf.tensordot(tensor1, tf.transpose(tensor2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[67.996216, 72.29039 , 70.0408  , 78.776566, 74.27845 ],
       [68.932205, 67.911125, 66.19202 , 73.86763 , 72.70264 ],
       [75.368546, 76.299126, 71.6873  , 83.935974, 80.64215 ],
       [70.1219  , 70.58983 , 69.68103 , 79.3739  , 76.150696],
       [68.195366, 70.41446 , 67.80717 , 75.09886 , 73.66534 ]],
      dtype=float32)>

6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].


In [25]:
tensor = tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1)
tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.5332352 , 0.22339427, 0.8115331 ],
        [0.62276936, 0.77960443, 0.95989835],
        [0.9323398 , 0.19727194, 0.40570462],
        ...,
        [0.9856607 , 0.63980305, 0.5606215 ],
        [0.2514435 , 0.02031493, 0.37141192],
        [0.16835153, 0.3351475 , 0.90194285]],

       [[0.27834105, 0.53338945, 0.32615876],
        [0.7569313 , 0.9964287 , 0.6743741 ],
        [0.35068655, 0.04260409, 0.60139394],
        ...,
        [0.66536367, 0.20765471, 0.7695987 ],
        [0.69921803, 0.19102895, 0.78597796],
        [0.08460498, 0.9201888 , 0.8487327 ]],

       [[0.15580916, 0.6898861 , 0.2937007 ],
        [0.23140275, 0.09369922, 0.6111605 ],
        [0.85097003, 0.70751894, 0.4381703 ],
        ...,
        [0.18239057, 0.05327666, 0.3428619 ],
        [0.50860035, 0.7567121 , 0.24162114],
        [0.99426484, 0.5678729 , 0.29078043]],

       ...,

       [[0.05065584, 0.67348444, 0.02117562],
        [0.18

7. Find the min and max values of the tensor you created in 6 along the first axis.


In [30]:
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99999964>

In [31]:
tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=8.46386e-06>

8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [36]:
tensor = tf.random.uniform(shape=[1,224,224,3])
print(tensor)

tf.Tensor(
[[[[0.79789436 0.45689487 0.10143828]
   [0.97620904 0.93344605 0.30395758]
   [0.5619936  0.8240273  0.38661337]
   ...
   [0.7978246  0.3320086  0.02858186]
   [0.17832303 0.9813664  0.5090499 ]
   [0.2166816  0.5225229  0.5751854 ]]

  [[0.44782186 0.01735008 0.31195116]
   [0.85116065 0.08604419 0.9463415 ]
   [0.8118248  0.348639   0.8896588 ]
   ...
   [0.50054026 0.8395488  0.6652465 ]
   [0.7498218  0.19712579 0.62710524]
   [0.1532526  0.9839438  0.895007  ]]

  [[0.9698578  0.11666012 0.59377456]
   [0.23433614 0.68195724 0.8822832 ]
   [0.162269   0.49035144 0.13090944]
   ...
   [0.44633365 0.80074525 0.00837314]
   [0.64181507 0.1930021  0.83110857]
   [0.17653906 0.70281553 0.5400003 ]]

  ...

  [[0.23808789 0.20121658 0.50350916]
   [0.6904472  0.32307696 0.361341  ]
   [0.5116615  0.67232597 0.62472415]
   ...
   [0.06423676 0.4620396  0.5461135 ]
   [0.39095318 0.11754096 0.21101582]
   [0.15720093 0.067029   0.7041198 ]]

  [[0.5103861  0.7051177  0.350843

In [41]:
tensor_squeeze = tf.squeeze(tensor)
tensor_squeeze, tensor_squeeze.shape

(<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
 array([[[0.79789436, 0.45689487, 0.10143828],
         [0.97620904, 0.93344605, 0.30395758],
         [0.5619936 , 0.8240273 , 0.38661337],
         ...,
         [0.7978246 , 0.3320086 , 0.02858186],
         [0.17832303, 0.9813664 , 0.5090499 ],
         [0.2166816 , 0.5225229 , 0.5751854 ]],
 
        [[0.44782186, 0.01735008, 0.31195116],
         [0.85116065, 0.08604419, 0.9463415 ],
         [0.8118248 , 0.348639  , 0.8896588 ],
         ...,
         [0.50054026, 0.8395488 , 0.6652465 ],
         [0.7498218 , 0.19712579, 0.62710524],
         [0.1532526 , 0.9839438 , 0.895007  ]],
 
        [[0.9698578 , 0.11666012, 0.59377456],
         [0.23433614, 0.68195724, 0.8822832 ],
         [0.162269  , 0.49035144, 0.13090944],
         ...,
         [0.44633365, 0.80074525, 0.00837314],
         [0.64181507, 0.1930021 , 0.83110857],
         [0.17653906, 0.70281553, 0.5400003 ]],
 
        ...,
 
        [[0.23808789, 0.20121658

9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [45]:
tensor = tf.constant([4,2,1,3,6,7,22,100, 123, -4])

tf.argmax(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=8>

10. One-hot encode the tensor you created in 9.


In [46]:
tf.one_hot(tensor, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

Try to create a series of tensor functions to calculate your most recent grocery bill (it's okay if you don't use the names of the items, just the price in numerical form).
* How would you calculate your grocery bill for the month and for the year using tensors?

In [47]:
prices = tf.constant([120, 300, 100, 450, 342, 200, 12, 123, 22])
quantity = tf.constant([1, 4, 3, 1, 2, 6, 4, 1, 2])

In [50]:
bill = tf.reduce_sum(prices)
bill

# We can calculate bill for month and year by making seperate tensors for month and year

<tf.Tensor: shape=(), dtype=int32, numpy=1669>

### Tensorflow quick start for beginners

In [51]:
import tensorflow as tf

In [52]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

In [56]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [58]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.01786301, -0.00839287,  0.33456674, -0.22109737, -0.0782677 ,
         0.2176723 , -0.02206556, -0.16001953,  0.2603299 ,  0.06910446]],
      dtype=float32)

In [59]:
tf.nn.softmax(predictions).numpy()

array([[0.09626021, 0.0937657 , 0.13212636, 0.07579971, 0.08743751,
        0.11755006, 0.09249239, 0.08057371, 0.12267295, 0.10132129]],
      dtype=float32)

In [60]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [61]:
loss_fn(y_train[:1], predictions).numpy()

2.140891

In [62]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [63]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - accuracy: 0.8616 - loss: 0.4803
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9561 - loss: 0.1480
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9672 - loss: 0.1078
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9723 - loss: 0.0876
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9761 - loss: 0.0743
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9807 - loss: 0.0607
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9825 - loss: 0.0549
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9837 - loss: 0.0505
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9855 - loss: 0.0449
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9861 - loss: 0.0415


In [64]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9802 - loss: 0.0688


[0.06883683800697327, 0.9801999926567078]

In [66]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten_3 (Flatten)             │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 128)            │       100,480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 305,312 (1.16 MB)

 Trainable params: 101,770 (397.54 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 203,542 (795.09 KB)